import { notFound } from "next/navigation";
import { AmountSummary } from "@/components/AmountSummary";
import { ButtonLink } from "@/components/Button";
import { Banner, DocumentCard, ErrorState } from "@/components/Surfaces";
import { Sending } from "@/components/Sending";
import { ShareStamp } from "@/components/ShareStamp";
import { StampBlock } from "@/components/StampBlock";
import { nrsQrPayload } from "@/lib/nrs";
import { copy, formatDateTime, BRAND, TRUST } from "@/lib/copy";
import { formatNaira, kobo, koboToWords } from "@/lib/money";
import {
  caseNumber,
  ERROR_MAP,
  formatOffendingValue,
  isSimulatedGateway,
} from "@/lib/gateway";
import { qrSvg } from "@/lib/qr";
import { requireSupplier } from "@/lib/auth/require";
import { getInvoiceForSupplier } from "@/lib/services/invoices";
import { finishTransmission, recordShare } from "../../actions";
import shell from "@/components/shell.module.css";

export const dynamic = "force-dynamic";

type Invoice = NonNullable<Awaited<ReturnType<typeof getInvoiceForSupplier>>>;

/**
 * S8, S9, S10 and S12 in one route.
 *
 * That is deliberate: a failure is not a different place, it is the same
 * document in a different state, and keeping the frame identical is what makes
 * a rejection recoverable rather than disorienting (Phase 15.2).
 */
export default async function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const principal = await requireSupplier();
  const { id } = await params;
  const invoice = await getInvoiceForSupplier(id, principal.supplierId);
  if (!invoice) notFound();

  switch (invoice.status) {
    case "draft":
      return (
        <ErrorState
          status="draft"
          what={copy.detail.draftHeading}
          why={copy.detail.draftWhy}
          reassurance={TRUST.saved}
          action={
            <ButtonLink href={`/s/invoice/${invoice.id}/review`}>{copy.detail.draftCta}</ButtonLink>
          }
        />
      );
    case "queued":
    case "sending":
      return <Sending invoiceId={invoice.id} run={finishTransmission} />;
    case "rejected":
      return <NotStamped invoice={invoice} />;
    default:
      return <Stamped invoice={invoice} />;
  }
}

/** S9 — the hero. */
async function Stamped({ invoice }: { invoice: Invoice }) {
  const [line] = invoice.lines;
  const amount = formatNaira(kobo(invoice.totalKobo));
  const qr = invoice.irn ? await qrSvg(nrsQrPayload(invoice.irn)) : null;

  const shareText = copy.stamped.shareText({
    number: invoice.invoiceNumber,
    supplier: invoice.supplier.businessName,
    amount,
    irn: invoice.irn ?? "",
  });

  return (
    <div className={shell.stack}>
      {/* The contingency in Architecture §16.7: a demo running on the fake
          gateway is labelled out loud, never quietly. */}
      {isSimulatedGateway() ? <Banner tone="warning">{copy.stamped.simulated}</Banner> : null}

      <DocumentCard
        label={copy.a11y.stampedCard(invoice.invoiceNumber, koboToWords(kobo(invoice.totalKobo)))}
      >
        <StampBlock
          irn={invoice.irn ?? ""}
          stampedAt={invoice.stampedAt ? formatDateTime(invoice.stampedAt) : ""}
          pressed
        />

        <h1 className={shell.display} style={{ marginTop: "var(--space-5)" }}>
          {copy.stamped.heading}
        </h1>
        <p className={shell.lede}>
          {copy.stamped.invoiceLine(invoice.invoiceNumber, invoice.organisation.legalName)}
        </p>

        <div style={{ marginTop: "var(--space-4)" }}>
          <AmountSummary
            subtotalKobo={invoice.subtotalKobo}
            vatKobo={invoice.vatKobo}
            totalKobo={invoice.totalKobo}
            vatBasisPoints={line.vatBasisPoints}
          />
        </div>

        <div className={shell.displayRow} style={{ marginTop: "var(--space-5)" }}>
          <span className={shell.displayLabel}>{copy.stamped.reference}</span>
          <span className={shell.monoLarge}>{invoice.irn}</span>
        </div>
        {invoice.stampedAt ? (
          <p className={shell.note}>{copy.stamped.at(formatDateTime(invoice.stampedAt))}</p>
        ) : null}

        <div className={shell.row} style={{ marginTop: "var(--space-5)" }}>
          {qr ? (
            // Generated by our own encoder from an IRN we issued; no user
            // input reaches this markup.
            <span aria-hidden="true" dangerouslySetInnerHTML={{ __html: qr }} />
          ) : (
            <span className={shell.note}>{copy.stamped.qrFailed}</span>
          )}
          <span className={shell.note} style={{ flex: 1 }}>
            {copy.stamped.disclaimer}
          </span>
        </div>
      </DocumentCard>

      <ShareStamp
        text={shareText}
        pdfHref={`/s/invoice/${invoice.id}/pdf`}
        onShared={recordShare.bind(null, invoice.id)}
      />
    </div>
  );
}

/** S10 — four causes, four copies, one frame. */
function NotStamped({ invoice }: { invoice: Invoice }) {
  const mapping = invoice.failureCode ? ERROR_MAP[invoice.failureCode] : undefined;
  const reason = mapping?.reason ?? "the NRS returned something we have not seen before";
  const transmission = invoice.transmissions.at(-1);
  const offending =
    transmission?.offendingValue && invoice.failureCode
      ? formatOffendingValue(invoice.failureCode, transmission.offendingValue)
      : (transmission?.offendingValue ?? undefined);
  const buyerName = invoice.organisation.legalName;

  if (invoice.failureFault === "platform") {
    return (
      <ErrorState
        status="rejected"
        what={copy.notStamped.platform.heading}
        why={copy.notStamped.platform.why}
        next={copy.notStamped.platform.next}
        reassurance={copy.notStamped.saved}
        action={
          <a href={`tel:${BRAND.supportPhoneTel}`} className={shell.textLink}>
            {copy.notStamped.platform.cta}
          </a>
        }
      />
    );
  }

  if (invoice.failureFault === "supplier") {
    return (
      <ErrorState
        status="rejected"
        what={copy.notStamped.supplier.heading}
        why={copy.notStamped.supplier.why(reason)}
        offendingValue={offending}
        next={copy.notStamped.supplier.next}
        reassurance={copy.notStamped.saved}
        // Carries the rejected invoice forward, so "edit" means edit rather
        // than "type all of that again".
        action={
          <ButtonLink href={`/s/new?from=${invoice.id}`}>
            {copy.notStamped.supplier.cta}
          </ButtonLink>
        }
      />
    );
  }

  if (invoice.failureFault === "buyer") {
    return (
      <ErrorState
        status="rejected"
        what={copy.notStamped.buyer.heading}
        why={copy.notStamped.buyer.why(reason, buyerName)}
        offendingValue={offending}
        next={copy.notStamped.buyer.next}
        reassurance={copy.notStamped.saved}
        // Nothing for the supplier to do. Saying so is the action.
        action={<p className={shell.note}>{copy.notStamped.buyer.acknowledged}</p>}
      />
    );
  }

  // A retryable failure leaves the invoice queued with a next attempt booked.
  // Once the attempts are spent the row is rejected and nothing else will
  // happen to it on its own, so the screen stops saying that it will.
  const stillRetrying = Boolean(transmission?.nextAttemptAt);
  const reference = caseNumber(transmission?.id ?? invoice.id);

  return (
    <ErrorState
      status="rejected"
      what={
        stillRetrying ? copy.notStamped.neither.heading : copy.notStamped.neither.finalHeading
      }
      why={copy.notStamped.neither.why(reason)}
      next={
        stillRetrying
          ? copy.notStamped.neither.next(reference)
          : copy.notStamped.neither.exhausted(reference)
      }
      reassurance={copy.notStamped.saved}
      action={
        <a href={`tel:${BRAND.supportPhoneTel}`} className={shell.textLink}>
          {copy.notStamped.neither.cta}
        </a>
      }
    />
  );
}
